os:
  - osx
install:
  - brew install python --universal --framework
  - brew install wxpython
  - "pip install appdirs pyserial simplejson py2app hidapi Cython mock pyobjc-core pyobjc-framework-cocoa pyobjc-framework-quartz"
script:
  - python setup.py
  - python run_tests.py
